"""make disease fields required

Revision ID: 6b635e194ce1
Revises: d7e566bbdf7e
Create Date: 2026-09-09 11:36:33.858854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b635e194ce1'
down_revision: Union[str, Sequence[str], None] = 'd7e566bbdf7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diseases', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('diseases', 'symptoms',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('diseases', 'treatment_plan',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('diseases', 'recommendations',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diseases', 'recommendations',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('diseases', 'treatment_plan',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('diseases', 'symptoms',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('diseases', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
