"""initial tables

Revision ID: 999dac7d66d3
Revises: 
Create Date: 2026-08-16 22:53:48.373591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999dac7d66d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('treatment_recommendations', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('disease_id')
    )
    op.create_index(op.f('ix_diseases_disease_id'), 'diseases', ['disease_id'], unique=False)
    op.create_index(op.f('ix_diseases_name'), 'diseases', ['name'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('farmer', 'admin', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_admins_admin_id'), 'admins', ['admin_id'], unique=False)
    op.create_table('farmers',
    sa.Column('farmer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auth_provider', sa.Enum('local', 'google', name='authprovider'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('farmer_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_farmers_farmer_id'), 'farmers', ['farmer_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('diagnosed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.disease_id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.farmer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('diagnosis_id')
    )
    op.create_index(op.f('ix_diagnoses_diagnosis_id'), 'diagnoses', ['diagnosis_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'approved', 'rejected', name='paymentstatus'), nullable=False),
    sa.Column('transaction_ref', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.diagnosis_id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.farmer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('diagnosis_id')
    )
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_diagnoses_diagnosis_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_farmers_farmer_id'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_admins_admin_id'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_diseases_name'), table_name='diseases')
    op.drop_index(op.f('ix_diseases_disease_id'), table_name='diseases')
    op.drop_table('diseases')
    # ### end Alembic commands ###
