"""add description, treatment_plan, recommendations to diseases

Revision ID: d7e566bbdf7e
Revises: e763bb493783
Create Date: 2026-09-08 14:06:13.829204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e566bbdf7e'
down_revision: Union[str, Sequence[str], None] = 'e763bb493783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diseases', sa.Column('name_en', sa.String(length=100), nullable=False))
    op.add_column('diseases', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('diseases', sa.Column('treatment_plan', sa.Text(), nullable=True))
    op.add_column('diseases', sa.Column('recommendations', sa.Text(), nullable=True))
    op.create_index(op.f('ix_diseases_name_en'), 'diseases', ['name_en'], unique=True)
    op.drop_column('diseases', 'treatment_recommendations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diseases', sa.Column('treatment_recommendations', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_diseases_name_en'), table_name='diseases')
    op.drop_column('diseases', 'recommendations')
    op.drop_column('diseases', 'treatment_plan')
    op.drop_column('diseases', 'description')
    op.drop_column('diseases', 'name_en')
    # ### end Alembic commands ###
