"""add plants table without location

Revision ID: e763bb493783
Revises: fa22cb33a804
Create Date: 2026-09-07 14:50:38.873938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e763bb493783'
down_revision: Union[str, Sequence[str], None] = 'fa22cb33a804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.farmer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plant_id')
    )
    op.create_index(op.f('ix_plants_plant_id'), 'plants', ['plant_id'], unique=False)
    op.add_column('diagnoses', sa.Column('plant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'diagnoses', 'plants', ['plant_id'], ['plant_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diagnoses', type_='foreignkey')
    op.drop_column('diagnoses', 'plant_id')
    op.drop_index(op.f('ix_plants_plant_id'), table_name='plants')
    op.drop_table('plants')
    # ### end Alembic commands ###
